"""Add PinnedLead model and relationships

Revision ID: 3e5e014b2973
Revises: add_lead_lifecycle_state
Create Date: 2026-07-10 12:17:32.370083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5e014b2973'
down_revision: Union[str, Sequence[str], None] = 'add_lead_lifecycle_state'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinned_leads',
    sa.Column('pinned_lead_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pinned_lead_id')
    )
    op.create_index(op.f('ix_pinned_leads_lead_id'), 'pinned_leads', ['lead_id'], unique=False)
    op.create_index(op.f('ix_pinned_leads_organization_id'), 'pinned_leads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pinned_leads_user_id'), 'pinned_leads', ['user_id'], unique=False)
    op.drop_table('lead_import_batch_counters')
    op.drop_constraint(op.f('invitations_token_hash_key'), 'invitations', type_='unique')
    op.drop_index(op.f('ix_invitations_token_hash'), table_name='invitations')
    op.create_index(op.f('ix_invitations_token_hash'), 'invitations', ['token_hash'], unique=True)
    op.drop_index(op.f('ix_lead_assignments_assigned_to'), table_name='lead_assignments')
    op.drop_index(op.f('ix_lead_assignments_lead_id'), table_name='lead_assignments')
    op.drop_index(op.f('ix_lead_scores_lead_id'), table_name='lead_scores')
    op.drop_index(op.f('ix_leads_is_deleted'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_status'), table_name='leads')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_staff_id_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_staff_id'), table_name='users')
    op.create_index(op.f('ix_users_staff_id'), 'users', ['staff_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_staff_id'), table_name='users')
    op.create_index(op.f('ix_users_staff_id'), 'users', ['staff_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_staff_id_key'), 'users', ['staff_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_leads_lead_status'), 'leads', ['lead_status'], unique=False)
    op.create_index(op.f('ix_leads_is_deleted'), 'leads', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_lead_scores_lead_id'), 'lead_scores', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_assignments_lead_id'), 'lead_assignments', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_assignments_assigned_to'), 'lead_assignments', ['assigned_to'], unique=False)
    op.drop_index(op.f('ix_invitations_token_hash'), table_name='invitations')
    op.create_index(op.f('ix_invitations_token_hash'), 'invitations', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('invitations_token_hash_key'), 'invitations', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.create_table('lead_import_batch_counters',
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('batch_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('counter', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('lead_import_batch_counters_organization_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('organization_id', 'batch_date', name=op.f('lead_import_batch_counters_pkey'))
    )
    op.drop_index(op.f('ix_pinned_leads_user_id'), table_name='pinned_leads')
    op.drop_index(op.f('ix_pinned_leads_organization_id'), table_name='pinned_leads')
    op.drop_index(op.f('ix_pinned_leads_lead_id'), table_name='pinned_leads')
    op.drop_table('pinned_leads')
    # ### end Alembic commands ###
